services:
  - type: web
    name: clm-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn clm_backend.wsgi
    healthCheckPath: /health/
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DISABLE_COLLECTSTATIC
        value: 1
      - key: DEBUG
        value: false
